# -*- coding: utf-8 -*-
"""MINIST_Distinguish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmpSPw6Cz8gmo4SeBi5Q89i29jGDJgma
"""

# Install required libraries (run once)
!pip install tensorflow matplotlib scikit-learn

# Import libraries
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

print("✅ Libraries imported!")
print(f"TensorFlow version: {tf.__version__}")

# Load MNIST dataset
print("📥 Loading MNIST dataset...")
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

print(f"Training set: {x_train.shape} | Labels: {y_train.shape}")
print(f"Test set: {x_test.shape} | Labels: {y_test.shape}")
print(f"Label range: {y_train.min()} to {y_train.max()}")

# Show sample images
plt.figure(figsize=(10, 4))
for i in range(8):
    plt.subplot(2, 4, i+1)
    plt.imshow(x_train[i], cmap='gray')
    plt.title(f'Label: {y_train[i]}')
    plt.axis('off')
plt.tight_layout()
plt.show()

# Normalize pixel values (0-255 → 0-1)
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# Reshape for CNN (add channel dimension)
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)

# One-hot encode labels
y_train_cat = keras.utils.to_categorical(y_train, 10)
y_test_cat = keras.utils.to_categorical(y_test, 10)

# Create validation split
x_train_split, x_val, y_train_split_cat, y_val_cat = train_test_split(
    x_train, y_train_cat, test_size=0.1, random_state=42
)

print("✅ Preprocessing complete!")
print(f"Training: {x_train_split.shape} | Val: {x_val.shape} | Test: {x_test.shape}")

# Build CNN model
model = keras.Sequential([
    keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    keras.layers.MaxPooling2D((2, 2)),
    keras.layers.Conv2D(64, (3, 3), activation='relu'),
    keras.layers.MaxPooling2D((2, 2)),
    keras.layers.Conv2D(64, (3, 3), activation='relu'),
    keras.layers.Flatten(),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(10, activation='softmax')
])

# Compile
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

# Train model
print("🚀 Training model...")
history = model.fit(x_train_split, y_train_split_cat,
                   batch_size=32,
                   epochs=50,
                   validation_data=(x_val, y_val_cat),
                   verbose=1)
print("✅ Training complete!")

# Plot training curves
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

# Test evaluation
test_loss, test_accuracy = model.evaluate(x_test, y_test_cat, verbose=0)
print(f"📊 Test Results:")
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f} ({test_accuracy*100:.2f}%)")

# Prediction visualization
def plot_predictions(model, x_test, y_test, num_samples=12):
    predictions = model.predict(x_test[:num_samples])
    predicted_classes = np.argmax(predictions, axis=1)

    plt.figure(figsize=(15, 5))
    for i in range(num_samples):
        plt.subplot(3, 4, i+1)
        plt.imshow(x_test[i].squeeze(), cmap='gray')
        color = 'green' if predicted_classes[i] == y_test[i] else 'red'
        plt.title(f'True: {y_test[i]}\nPred: {predicted_classes[i]}', color=color)
        plt.axis('off')
    plt.tight_layout()
    plt.show()

plot_predictions(model, x_test, y_test)

# Save model
model.save('mnist_digit_model.h5')
print("💾 Model saved as 'mnist_digit_model.h5'")

# Test single prediction
sample_idx = 42
prediction = model.predict(x_test[sample_idx:sample_idx+1])
predicted_digit = np.argmax(prediction)

plt.figure(figsize=(4, 4))
plt.imshow(x_test[sample_idx].squeeze(), cmap='gray')
plt.title(f'Predicted: {predicted_digit} (True: {y_test[sample_idx]})')
plt.axis('off')
plt.show()

print(f"✅ Ready for production use!")

# Download the trained model
from google.colab import files

# Save model in multiple formats
model.save('mnist_digit_model.h5')

print("📥 Downloading model files...")
files.download('mnist_digit_model.h5')
print("✅ Model downloaded! Keep these files safe.")

from google.colab import files
from PIL import Image
import numpy as np

print("📤 Upload your handwritten digit image (28x28px grayscale recommended)")
print("Supported formats: PNG, JPG, JPEG")

# Upload image
uploaded = files.upload()

# Process first uploaded image
filename = list(uploaded.keys())[0]
print(f"Processing: {filename}")

# Load and preprocess image
img = Image.open(filename).convert('L')  # Convert to grayscale
img = img.resize((28, 28))  # Resize to 28x28
img_array = np.array(img) / 255.0  # Normalize
img_array = img_array.reshape(1, 28, 28, 1)  # Reshape for model

# Show original image
plt.figure(figsize=(6, 6))
plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title('Your Image')
plt.axis('off')

# Predict
prediction = model.predict(img_array)
predicted_digit = np.argmax(prediction)
confidence = np.max(prediction) * 100

plt.subplot(1, 2, 2)
plt.imshow(img_array.squeeze(), cmap='gray')
plt.title(f'Predicted: {predicted_digit}\nConfidence: {confidence:.1f}%')
plt.axis('off')

plt.tight_layout()
plt.show()

print(f"🎯 Prediction: {predicted_digit}")
print(f"📊 Confidence: {confidence:.1f}%")
print(f"📈 All probabilities: {dict(zip(range(10), np.round(prediction[0]*100, 1)))}")

from google.colab import files
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

print("📤 Upload your handwritten digit image (28x28px grayscale recommended)")
print("Supported formats: PNG, JPG, JPEG,jfif")

# Upload image
uploaded = files.upload()

# Process first uploaded image
filename = list(uploaded.keys())[0]
print(f"Processing: {filename}")

# Load and preprocess image
img = Image.open(filename).convert('L')  # Convert to grayscale
img = img.resize((28, 28))  # Resize to 28x28
img_array = np.array(img) / 255.0  # Normalize
img_array = img_array.reshape(1, 28, 28, 1)  # Reshape for model

# Predict
prediction = model.predict(img_array)
predicted_digit = np.argmax(prediction)
confidence = np.max(prediction) * 100

# Create comprehensive visualization
fig = plt.figure(figsize=(16, 10))

# 1. Original vs Processed Image
plt.subplot(2, 3, 1)
plt.imshow(img, cmap='gray')
plt.title('Original Image', fontsize=14, fontweight='bold')
plt.axis('off')

plt.subplot(2, 3, 2)
plt.imshow(img_array.squeeze(), cmap='gray')
plt.title(f'Processed (28x28)\nPredicted: {predicted_digit}',
          fontsize=14, fontweight='bold', color='green' if confidence > 90 else 'orange')
plt.axis('off')

# 2. Confidence Bar Chart (highlighted winner)
plt.subplot(2, 3, 3)
colors = ['lightgray'] * 10
colors[predicted_digit] = 'gold' if confidence > 90 else 'orange'
bars = plt.bar(range(10), prediction[0]*100, color=colors, alpha=0.8, edgecolor='black')
plt.title('Confidence Scores (%)', fontsize=14, fontweight='bold')
plt.xlabel('Digit')
plt.ylabel('Confidence %')
plt.xticks(range(10))
plt.ylim(0, 100)

# Highlight max bar
bars[predicted_digit].set_alpha(1.0)
bars[predicted_digit].set_color('darkgreen' if confidence > 90 else 'darkorange')

# Add confidence text
plt.text(predicted_digit, confidence + 1, f'{confidence:.1f}%',
         ha='center', va='bottom', fontweight='bold', fontsize=12, color='white')

# 3. Top 5 Probabilities Horizontal Bar
plt.subplot(2, 3, (4, 6))
top5_indices = np.argsort(prediction[0])[::-1][:5]
top5_probs = prediction[0][top5_indices] * 100

colors_top5 = ['gold' if i == predicted_digit else 'silver' for i in top5_indices]
bars_top5 = plt.barh(range(5), top5_probs, color=colors_top5, alpha=0.9, edgecolor='black')
plt.title('Top 5 Predictions', fontsize=14, fontweight='bold')
plt.xlabel('Confidence %')
plt.yticks(range(5), [f'Digit {top5_indices[i]}' for i in range(5)])
plt.xlim(0, 100)

# Add percentage labels
for i, (bar, prob) in enumerate(zip(bars_top5, top5_probs)):
    plt.text(prob + 1, i, f'{prob:.1f}%', va='center', fontweight='bold')

plt.tight_layout()
plt.show()

# Print detailed results
print(f"\n🎯 FINAL PREDICTION: {predicted_digit}")
print(f"📊 CONFIDENCE: {confidence:.1f}%")
print(f"\n📈 ALL PROBABILITIES:")
for i in range(10):
    print(f"  Digit {i}: {prediction[0][i]*100:.1f}%")
print(f"\n🏆 Top 5: {dict(zip(top5_indices, np.round(top5_probs, 1)))}")